### PR TITLE
VRVU-39:Add Birth weight field to registration

### PR DESCRIPTION
**Pull request by sherrif10**
PR  https://sd-vxnaid.atlassian.net/browse/VRVU-39
cc @jdolkowski  @pwargulak 
Screenshot 2024-06-13 133231

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @jdolkowski   . basically i changed few things which are only front end, the only part remaining is to be able to save birthweight.  Let me know  your suggestion.

Screenshot 2024-06-14 141747

**Comment by jdolkowski** [comment]
@sherrif10 I added comments in code

**Comment by jdolkowski** [comment]
ctrl + shift + f and search for todo/TODO phrase

**Comment by jdolkowski** [comment]
image
also remember to add a key of the attribute in the admin panel on the web app

**Comment by jdolkowski** [comment]
https://github.com/johnsonandjohnson/vxnaid/pull/23
due to git issues this feature was moved to a new PR: https://github.com/johnsonandjohnson/vxnaid/pull/23

**Pull request closed without merging**
